### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by konstantin83** [marco-prontera/vite-plugin-css-injected-by-js#131]
Hey! I'm absolutely newbie with Vite. I got a simple Vue project, that is building an index.html file with <script> and <style> in it.
While I need to output only single .js file with all styles in it, that would be unpacked when script is imported to a website.
AI advised your plugin. But I get it working. This is the error I get after `npm run build`:
```bash
vite v4.5.1 building for production...
✓ 64 modules transformed.
rendering chunks (1)...[vite-plugin-css-injected-by-js] Unable to locate the JavaScript asset for adding the CSS injection code. It is recommended to review your configurations.
✓ built in 546ms
error during build:
Error: Unable to locate the JavaScript asset for adding the CSS injection code. It is recommended to review your configurations.
    at /Users/salah/www/search/uprav-js/node_modules/vite-plugin-css-injected-by-js/dist/cjs/utils.js:186:19
    at Generator.next (<anonymous>)
    at /Users/salah/www/search/uprav-js/node_modules/vite-plugin-css-injected-by-js/dist/cjs/utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/salah/www/search/uprav-js/node_modules/vite-plugin-css-injected-by-js/dist/cjs/utils.js:4:12)
    at globalCssInjection (/Users/salah/www/search/uprav-js/node_modules/vite-plugin-css-injected-by-js/dist/cjs/utils.js:183:12)
    at Object.<anonymous> (/Users/salah/www/search/uprav-js/node_modules/vite-plugin-css-injected-by-js/dist/cjs/index.js:73:61)
    at Generator.next (<anonymous>)
    at /Users/salah/www/search/uprav-js/node_modules/vite-plugin-css-injected-by-js/dist/cjs/index.js:8:71
    at new Promise (<anonymous>)
```

My `vite.config.js` is:
```js
import { fileURLToPath, URL } from "node:url";

import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { viteSingleFile } from "vite-plugin-singlefile";

import cssInjectedByJsPlugin from "vite-plugin-css-injected-by-js";

// https://vitejs.dev/config/
/** @type {import('vite').UserConfig} */
export default defineConfig({
  plugins: [vue(), viteSingleFile(), cssInjectedByJsPlugin()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: false,
        inlineDynamicImports: true,
        entryFileNames: "[name].js", // currently does not work for the legacy bundle
        assetFileNames: "[name].[ext]", // currently does not work for images
      },
    },
  },
});
```

Maybe you can see what seems to be the problem?

**Comment by konstantin83** [comment]
Suddenly figured out that everything works just fine without `viteSingleFile(), ` in plugins array.
But still `index.html` is created. Is it possible to build just a single file `index.js`?

**Comment by corradopetrelli** [comment]
Hello @konstantin83, ca you could send the example? by doing so we can faithfully reproduce the problem locally

**Comment by marco-prontera** [comment]
> Suddenly figured out that everything works just fine without `viteSingleFile(), ` in plugins array.
> 
> But still `index.html` is created. Is it possible to build just a single file `index.js`?

Maybe you should consider using the library mode https://vitejs.dev/guide/build#library-mode.
